# Generated by Django 4.1.3 on 2022-11-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_auctionlistings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListings',
            new_name='AuctionListing',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
