# Generated by Django 4.1.3 on 2022-11-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctionlistings_auctionlisting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='user',
        ),
    ]
