# Generated by Django 4.1.3 on 2022-11-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='user',
        ),
    ]
